INSERT INTO EQUIPO VALUES ('Real Club Recreativo de Huelva','Rec._Huelva','Huelva Recreation Club','Huelva',1889,NULL);
INSERT INTO EQUIPO VALUES ('Athletic Club','Ath._Bilbao','Athletic Club','Bilbao',1898,1901);
INSERT INTO EQUIPO VALUES ('Futbol Club Barcelona','Barcelona','Foot-Ball Club Barcelona','Barcelona',1899,NULL);
INSERT INTO EQUIPO VALUES ('Real Club Deportivo Espanol','Espanyol','Sociedad Espanola de Foot-Ball','Barcelona',1900,NULL);
INSERT INTO EQUIPO VALUES ('Real Madrid Club de Futbol','Real_Madrid','(Sociedad) Madrid Foot-Ball Club','Madrid',1900,1902);
INSERT INTO EQUIPO VALUES ('Centre dEsports Sabadell Futbol Club','Sabadell','Centre d''Esports Sabadell','Sabadell',1901,1906);
INSERT INTO EQUIPO VALUES ('Club Atletico de Madrid','At._Madrid','Athletic Club (Sucursal de Madrid)','Madrid',1903,NULL);
INSERT INTO EQUIPO VALUES ('Real Aviles Club de Futbol','Aviles','Aviles Sport Club','Aviles',1903,NULL);
INSERT INTO EQUIPO VALUES ('Real Sporting de Gijon','Sporting_Gijon','Sporting Gijones','Gijon',1905,NULL);
INSERT INTO EQUIPO VALUES ('Sevilla Futbol Club','Sevilla','Sevilla Foot-Ball Club','Sevilla',1890,1905);
INSERT INTO EQUIPO VALUES ('Real Club Deportivo Carabanchel','Carabanchel','Club Deportivo Carabanchel','Madrid',1906,1916);
INSERT INTO EQUIPO VALUES ('Real Club Deportivo de La Coruna','Dptivo._Coruna','Club Deportivo de la Sala Calvet','La Coruna',1906,NULL);
INSERT INTO EQUIPO VALUES ('Club Esportiu Europa','Europa','Club Deportivo Europa','Barcelona',1907,NULL);
INSERT INTO EQUIPO VALUES ('Real Betis Balompie','Betis','Sevilla Balompie','Sevilla',1907,1914);
INSERT INTO EQUIPO VALUES ('Gimnastica de Torrelavega','Torrelavega','Sociedad Gimnastica','Torrelavega',1907,NULL);
INSERT INTO EQUIPO VALUES ('Real Murcia Club de Futbol','Murcia','Levante Foot-Ball Club de Murcia','Murcia',1908,1920);
INSERT INTO EQUIPO VALUES ('Real Sociedad de Futbol','Real_Sociedad','Sociedad de Foot-Ball','San Sebastian',1909,NULL);
INSERT INTO EQUIPO VALUES ('Levante Union Deportiva','Levante','Levante Foot-Ball Club','Valencia',1909,NULL);
INSERT INTO EQUIPO VALUES ('Arenas Club de Guecho','Guecho','Arenas Foot-Ball Club','Guecho',1909,1910);
INSERT INTO EQUIPO VALUES ('Cadiz Club de Futbol','Cadiz','Cadiz Foot-Ball Club','Cadiz',1910,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Tenerife','Tenerife','Sporting Club Tenerife','Santa Cruz de Tenerife',1912,NULL);
INSERT INTO EQUIPO VALUES ('Real Balompedica Linense','Linense','Real Balompedica Linense','La Linea',1912,NULL);
INSERT INTO EQUIPO VALUES ('Algeciras Club de Futbol','Algeciras','Algeciras Club de Futbol','Algeciras',1912,NULL);
INSERT INTO EQUIPO VALUES ('Real Racing Club de Santander','Rac._Santander','Santander Racing Club','Santander',1913,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Basconia','Basconia','Club Deportivo Basconia','Basauri',1913,NULL);
INSERT INTO EQUIPO VALUES ('Real Club Deportivo de La Coruna B','Coruna_B','Fabril Foot-ball Club','La Coruna',1914,NULL);
INSERT INTO EQUIPO VALUES ('Club Gimnastic de Tarragona','Gimn._Tarragona','Club Gimnastico de Tarragona','Tarragona',1914,NULL);
INSERT INTO EQUIPO VALUES ('Hercules de Alicante Club de Futbol','Hercules','Hercules Foot-Ball Club','Alicante',1914,1922);
INSERT INTO EQUIPO VALUES ('Real Union Club','Real_Union','Real Union Club de Irun','Irun',1915,NULL);
INSERT INTO EQUIPO VALUES ('Real Club Deportivo Mallorca','Mallorca','(Sociedad) Alfonso XIII Foot-Ball Club','Palma de Mallorca',1916,NULL);
INSERT INTO EQUIPO VALUES ('Barakaldo Club de Futbol','Barakaldo','Baracaldo','Vizcaya',1917,NULL);
INSERT INTO EQUIPO VALUES ('Caudal Deportivo','Caudal','Mieres','Asturias',1918,NULL);
INSERT INTO EQUIPO VALUES ('Cartagena Futbol Club','Cartagena_F.C.','Cartagena','Murcia',1919,NULL);
INSERT INTO EQUIPO VALUES ('Unio Esportiva Figueres','Figueres','Union Sportiva Figueras','Figueras',1919,NULL);
INSERT INTO EQUIPO VALUES ('Club Polideportivo Cacereno','Cacereno','Club Deportivo Cacereno','Caceres',1919,NULL);
INSERT INTO EQUIPO VALUES ('Valencia Club de Futbol','Valencia','Valencia Foot-Ball Club','Valencia',1919,NULL);
INSERT INTO EQUIPO VALUES ('Racing Club de Ferrol','Ferrol','Ferrol','La Coruna',1919,NULL);
INSERT INTO EQUIPO VALUES ('Club Atletico Osasuna','Osasuna','Club Atletico Osasuna','Pamplona',1920,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Eldense','Eldense','Elda','Alicante',1921,NULL);
INSERT INTO EQUIPO VALUES ('Deportivo Alaves','Alaves','Club Deportivo Alaves','Vitoria',1921,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Castellon','Castellon','Castellon Foot-Ball Club','Castellon de la Plana',1919,1922);
INSERT INTO EQUIPO VALUES ('Elche Club de Futbol','Elche','Elche','Alicante',1922,NULL);
INSERT INTO EQUIPO VALUES ('Sociedad Deportiva Ponferradina','Ponferradina','Ponferrada','Leon',1921,1922);
INSERT INTO EQUIPO VALUES ('Tolosa Club de Futbol','Tolosa','Tolosa','Guipuzcoa',1922,NULL);
INSERT INTO EQUIPO VALUES ('Cultural y Deportiva Leonesa','Cult._Leonesa','Cultural y Deportiva Leonesa','Leon',1923,NULL);
INSERT INTO EQUIPO VALUES ('Real Club Celta de Vigo','Celta','Real Club Celta','Vigo',1923,NULL);
INSERT INTO EQUIPO VALUES ('Rayo Vallecano de Madrid','Rayo_Vallecano','Agrupacion Deportiva El Rayo','Madrid',1924,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Izarra','Izarra','Izarra Beti Aurrera','Estella',1924,NULL);
INSERT INTO EQUIPO VALUES ('Unio Esportiva Sant Andreu','Sant_Andreu','Unio Esportiva Sant Andreu','Barcelona',1925,NULL);
INSERT INTO EQUIPO VALUES ('Real Oviedo','Oviedo','Real Oviedo Foot-Ball Club','Oviedo',1926,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Mirandes','Mirandes','Club Deportivo Mirandes','Miranda de Ebro',1927,NULL);
INSERT INTO EQUIPO VALUES ('Real Valladolid Club de Futbol','Valladolid','Real Valladolid Deportivo','Valladolid',1928,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Leganes','Leganes','Leganes','Madrid',1928,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Alcoyano','Alcoyano','Club Deportivo Alcoyano','Alcoy',1928,NULL);
INSERT INTO EQUIPO VALUES ('Carrion Balompie','Carrion','Carrion Balompie','Carrion de los Cespedes',1928,NULL);
INSERT INTO EQUIPO VALUES ('Real Jaen Club de Futbol','Jaen','Sociedad Olimpica Jiennense','Jaen',1929,NULL);
INSERT INTO EQUIPO VALUES ('Girona Futbol Club','Girona','Gerona Foot-Ball Club','Gerona',1930,NULL);
INSERT INTO EQUIPO VALUES ('Granada Club de Futbol','Granada','Club Recreativo Granada','Granada',1931,NULL);
INSERT INTO EQUIPO VALUES ('Club Marino de Luanco','Luanco','Club Marino','Gozon',1931,NULL);
INSERT INTO EQUIPO VALUES ('Real Zaragoza','Zaragoza','Zaragoza Foot-Ball Club','Zaragoza',1932,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Logrones','Logrones','Club Deportivo Logrones','Logrono',1940,NULL);
INSERT INTO EQUIPO VALUES ('Albacete Balompie','Albacete','Albacete Foot-Ball Association','Albacete',1940,NULL);
INSERT INTO EQUIPO VALUES ('Pontevedra Club de Futbol','Pontevedra','Pontevedra Club de Futbol','Pontevedra',1941,NULL);
INSERT INTO EQUIPO VALUES ('Sociedad Deportiva Eibar','Eibar','Sociedad Deportiva Eibar','Eibar',1943,NULL);
INSERT INTO EQUIPO VALUES ('Valencia Club de Futbol Mestalla','Valencia_B','Club Deportivo Mestalla','Paterna',1944,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Numancia de Soria','Numancia','Club Deportivo Numancia','Soria',1945,NULL);
INSERT INTO EQUIPO VALUES ('Real Madrid Castilla Club de Futbol','Real_Madrid_B','Agrupacion Deportiva Plus Ultra','Madrid',1946,NULL);
INSERT INTO EQUIPO VALUES ('Villarreal Club de Futbol','Villarreal','Club Atletico Foghetecaz','Villarreal',1944,1947);
INSERT INTO EQUIPO VALUES ('Xerez Club Deportivo','Xerez','Jerez Club Deportivo','Jerez de la Frontera',1947,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Guadalajara','Guadalajara','Club Deportivo Guadalajara','Guadalajara',1947,NULL);
INSERT INTO EQUIPO VALUES ('Granada Club de Futbol B','Granada_74','Club Recreativo Granada','Granada',1947,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Puertollano','Puertollano','Club Deportivo Calvo Sotelo','Puertollano',1948,NULL);
INSERT INTO EQUIPO VALUES ('Union Deportiva Las Palmas','Las_Palmas','Union Deportiva Las Palmas','Las Palmas de Gran Canaria',1949,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Ourense','Ourense','Club Deportivo Orense','Orense',1952,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Lugo','Lugo','Club Deportivo Lugo','Lugo',1953,NULL);
INSERT INTO EQUIPO VALUES ('Cordoba Club de Futbol','Cordoba','Club Deportivo San Alvaro','Cordoba',1954,NULL);
INSERT INTO EQUIPO VALUES ('Club Atletico de Ceuta','Ceuta','Club Atletico de Ceuta','Ceuta',1956,NULL);
INSERT INTO EQUIPO VALUES ('Sociedad Deportiva Huesca','Huesca','Sociedad Deportiva Huesca','Huesca',1960,NULL);
INSERT INTO EQUIPO VALUES ('Union Popular de Langreo','Langreo','Union Popular de Langreo','Langreo',1961,NULL);
INSERT INTO EQUIPO VALUES ('Club Atletico de Madrid B','At._Madrid_B','Majadahonda','Madrid',1963,NULL);
INSERT INTO EQUIPO VALUES ('Bilbao Athletic','Ath._Bilbao_B','Club Atletico de Bilbao Amateur','Lezama',1964,NULL);
INSERT INTO EQUIPO VALUES ('Union Deportiva Logrones','Logrones_Varea','Club Deportivo Varea','Logrono',1967,NULL);
INSERT INTO EQUIPO VALUES ('Futbol Club Barcelona B','Barcelona_B','Barcelona Atletico','Barcelona',1970,NULL);
INSERT INTO EQUIPO VALUES ('Agrupacion Deportiva Alcorcon','Alcorcon','Alcorcon','Madrid',1971,NULL);
INSERT INTO EQUIPO VALUES ('Montilla Club de Futbol','Montilla','Club Deportivo Montilla','Montilla',1973,NULL);
INSERT INTO EQUIPO VALUES ('Getafe Club de Futbol','Getafe','Getafe','Madrid',1983,NULL);
INSERT INTO EQUIPO VALUES ('Real Burgos Club de Futbol','Burgos_(Real)','Real Burgos Club de Futbol','Burgos',1983,NULL);
INSERT INTO EQUIPO VALUES ('Union Deportiva Almeria','Almeria','Almeria Club de Futbol','Almeria',1989,NULL);
INSERT INTO EQUIPO VALUES ('Merida Union Deportiva','Merida','Union Deportiva Merida Promesas','Merida',1990,NULL);
INSERT INTO EQUIPO VALUES ('Malaga Club de Futbol','Malaga','Malaga Club de Futbol','Malaga',1994,NULL);
INSERT INTO EQUIPO VALUES ('Futbol Club Cartagena','Cartagena','Cartagonova Futbol Club','Cartagena',1995,NULL);
INSERT INTO EQUIPO VALUES ('Sestao River Club','Sestao','Sestao River Club','Sestao',1996,NULL);
INSERT INTO EQUIPO VALUES ('Sociedad Deportiva Compostela','Compostela','Sociedad Deportiva Campus Stellae','Santiago de Compostela',2004,NULL);
INSERT INTO EQUIPO VALUES ('Extremadura Union Deportiva','Extremadura','Extremadura Union Deportiva','Almendralejo',2007,NULL);
INSERT INTO EQUIPO VALUES ('Sociedad Deportiva Logrones','Logrones_Dep','Sociedad Deportiva Logrones','Logrono',2009,NULL);
INSERT INTO EQUIPO VALUES ('Tarrasa Olimpica 2010','Terrassa','Terrassa Olimpica 2010','Tarrasa',2009,NULL);
INSERT INTO EQUIPO VALUES ('Club Lleida Esportiu','Lleida','Club Lleida Esportiu','Lerida',2011,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Badajoz 1905','Badajoz','Club Deportivo Badajoz 1905','Badajoz',2012,NULL);
INSERT INTO EQUIPO VALUES ('Xerez Deportivo FC','Xerez_FC','Xerez Deportivo Futbol Club','Jerez de la Frontera',2013,NULL);
INSERT INTO EQUIPO VALUES ('Palamos Club de Futbol','Palamos','Palamos Club de Futbol','Palamos',1898,NULL);
INSERT INTO EQUIPO VALUES ('Union Deportiva Salamanca','Salamanca','Union Deportiva Espaniola','Salamanca',1923,NULL);
INSERT INTO EQUIPO VALUES ('Marbella Club de Futbol','Marbella','Marbella Foot-Ball Club','Marbella',1997,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Toledo','Toledo','Club Deportivo Toledo S.A.D','Toledo',1973,NULL);
INSERT INTO EQUIPO VALUES ('Villarreal Club de Fútbol SAD B','Villarreal_B',NULL,'Vila-real',1999,NULL);
INSERT INTO EQUIPO VALUES ('Club Polideportivo Ejido','Ejido','Club Polideportivo Ejido','El Ejido',2012,NULL);
INSERT INTO EQUIPO VALUES ('Atletico Malagueno S.A.D.','Malaga_B',NULL,'Malaga',1990,NULL);
INSERT INTO EQUIPO VALUES ('Linares Club de Futbol','Linares',NULL,'Linares',1960,NULL);
INSERT INTO EQUIPO VALUES ('Sevilla Atletico Club','Sevilla_B',NULL,'Sevilla',1958,NULL);
INSERT INTO EQUIPO VALUES ('Alicante Club de Fútbol','Alicante',NULL,'Alicante',1918,NULL);
INSERT INTO EQUIPO VALUES ('Univ.Las Palmas Club de Futbol','Univ.Las_Palmas',NULL,'Las Palmas de Gran Canaria',1994,NULL);
INSERT INTO EQUIPO VALUES ('Real Club Deportivo Mallorca B','Mallorca_B',NULL,'Mallorca',1967,NULL);
INSERT INTO EQUIPO VALUES ('Club de Futbol Palencia','Palencia',NULL,'Palencia',1975,NULL);
INSERT INTO EQUIPO VALUES ('Lorca Atletico Club de Futbol','Lorca','Sangonera Atletico','Lorca',1996,NULL);
INSERT INTO EQUIPO VALUES ('Union Deportiva Vecindario','Vecindario',NULL,'Las Palmas',1962,NULL);
INSERT INTO EQUIPO VALUES ('Ecija Balompie S.A.D','Ecija',NULL,'Ecija (Sevilla)',1939,NULL);
INSERT INTO EQUIPO VALUES ('Club de Futbol Jovent Mollerussa','Mollerussa',NULL,'Mollerussa',1968,NULL);
INSERT INTO EQUIPO VALUES ('Burgos Club de Fútbol','Burgos','Burgos Foot-ball Club','Burgos',1923,NULL);
INSERT INTO EQUIPO VALUES ('Union Deportiva Alzira','Alzira',NULL,'Alcira',1922,NULL);
INSERT INTO EQUIPO VALUES ('Club Deportivo Ensidesa','Ensidesa',NULL,'Aviles',1956,NULL);
INSERT INTO EQUIPO VALUES ('Real Zaragoza Deportivo Aragon','Zaragoza_B','Real Zaragoza Club Deportivo Aficionados','Zaragoza',1958,NULL);
INSERT INTO EQUIPO VALUES ('Orihuela Club de Futbol','Orihuela',NULL,'Orihuela',1993,NULL);
