INSERT INTO TENER VALUES('Rec._Huelva','Nuevo Colombino');
INSERT INTO TENER VALUES('Ath._Bilbao','San Mames');
INSERT INTO TENER VALUES('Barcelona','Camp Nou');
INSERT INTO TENER VALUES('Espanyol','Cornella-El Prat');
INSERT INTO TENER VALUES('Real_Madrid','Santiago Bernabeu');
INSERT INTO TENER VALUES('Sabadell','Nova Creu Alta');
INSERT INTO TENER VALUES('At._Madrid','Vicente Calderon');
INSERT INTO TENER VALUES('Aviles','Nuevo Roman Suarez Puerta');
INSERT INTO TENER VALUES('Sporting_Gijon','El Molinon');
INSERT INTO TENER VALUES('Sevilla','Ramon Sanchez Pizjuan');
INSERT INTO TENER VALUES('Dptivo._Coruna','Riazor');
INSERT INTO TENER VALUES('Europa','Nou Sardenya');
INSERT INTO TENER VALUES('Betis','Benito Villamarin');
INSERT INTO TENER VALUES('Murcia','Nueva Condomina');
INSERT INTO TENER VALUES('Real_Sociedad','Anoeta');
INSERT INTO TENER VALUES('Levante','Ciudad de Valencia');
INSERT INTO TENER VALUES('Cadiz','Ramon de Carranza');
INSERT INTO TENER VALUES('Tenerife','Heliodoro Rodriguez Lopez');
INSERT INTO TENER VALUES('Algeciras','Nuevo Mirador');
INSERT INTO TENER VALUES('Rac._Santander','El Sardinero');
INSERT INTO TENER VALUES('Basconia','Artunduaga');
INSERT INTO TENER VALUES('Gimn._Tarragona','Nou Estadi de Tarragona');
INSERT INTO TENER VALUES('Hercules','Jose Rico Perez');
INSERT INTO TENER VALUES('Real_Union','Stadium Gal');
INSERT INTO TENER VALUES('Mallorca','Iberostar Estadio');
INSERT INTO TENER VALUES('Barakaldo','Lasesarre');
INSERT INTO TENER VALUES('Caudal','Hermanos Antuna');
INSERT INTO TENER VALUES('Cartagena','Cartagonova');
INSERT INTO TENER VALUES('Toledo','Salto del Caballo');
INSERT INTO TENER VALUES('Villarreal_B','C.Dptva del Villarreal CF');
INSERT INTO TENER VALUES('Linares','Linarejos');
INSERT INTO TENER VALUES('Alicante','Jose Rico Perez');
INSERT INTO TENER VALUES ('Villarreal','El Madrigal');
INSERT INTO TENER VALUES ('Xerez','Chapin');
INSERT INTO TENER VALUES ('Guadalajara','Pedro Escartin');
INSERT INTO TENER VALUES ('Puertollano','Ciudad de Puertollano');
INSERT INTO TENER VALUES ('Las_Palmas','Gran Canaria En remodelacion');
INSERT INTO TENER VALUES ('Lugo','Angel Carro');
INSERT INTO TENER VALUES ('Cordoba','El Arcangel');
INSERT INTO TENER VALUES ('Huesca','El Alcoraz');
INSERT INTO TENER VALUES ('Logrones_Varea','Las Gaunas');
INSERT INTO TENER VALUES ('Barcelona_B','Mini Estadi');
INSERT INTO TENER VALUES ('Alcorcon','Santo Domingo 2');
INSERT INTO TENER VALUES ('Montilla','Estadio Municipal de Montilla');
INSERT INTO TENER VALUES ('Getafe','Coliseum Alfonso Perez');
INSERT INTO TENER VALUES ('Burgos','El Plantio');
INSERT INTO TENER VALUES ('Almeria','Juegos Mediterraneos');
INSERT INTO TENER VALUES ('Merida','Romano');
INSERT INTO TENER VALUES ('Malaga','Ciudad de Malaga');
INSERT INTO TENER VALUES ('Cartagena_F.C.','Cartagonova');
INSERT INTO TENER VALUES ('Sestao','Las Llanas');
INSERT INTO TENER VALUES ('Compostela','San Lazaro');
INSERT INTO TENER VALUES ('Extremadura','Francisco de la Hera');
INSERT INTO TENER VALUES ('Logrones_Dep','Las Gaunas');
INSERT INTO TENER VALUES ('Terrassa','Olimpic de Terrassa');
INSERT INTO TENER VALUES ('Lleida','Camp d''Esports');
INSERT INTO TENER VALUES ('Badajoz','Nuevo Vivero');
INSERT INTO TENER VALUES ('Valencia','Mestalla');
INSERT INTO TENER VALUES ('Osasuna','El Sadar');
INSERT INTO TENER VALUES ('Eldense','Pepico Amat');
INSERT INTO TENER VALUES ('Alaves','Mendizorroza');
INSERT INTO TENER VALUES ('Castellon','Castalia');
INSERT INTO TENER VALUES ('Elche','Manuel Martinez Valero');
INSERT INTO TENER VALUES ('Ponferradina','El Toralin');
INSERT INTO TENER VALUES ('Cult._Leonesa','Municipal');
INSERT INTO TENER VALUES ('Celta','Balaidos');
INSERT INTO TENER VALUES ('Rayo_Vallecano','Estadio de Vallecas');
INSERT INTO TENER VALUES ('Oviedo','Carlos Tartiere');
INSERT INTO TENER VALUES ('Mirandes','Anduva');
INSERT INTO TENER VALUES ('Valladolid','Jose Zorrilla');
INSERT INTO TENER VALUES ('Leganes','Butarque');
INSERT INTO TENER VALUES ('Jaen','La Victoria');
INSERT INTO TENER VALUES ('Girona','Municipal de Montilivi');
INSERT INTO TENER VALUES ('Granada','Los Carmenes');
INSERT INTO TENER VALUES ('Zaragoza','La Romareda');
INSERT INTO TENER VALUES ('Logrones','Las Gaunas');
INSERT INTO TENER VALUES ('Albacete','Carlos Belmonte');
INSERT INTO TENER VALUES ('Pontevedra','Pasaron');
INSERT INTO TENER VALUES ('Eibar','Ipurua');
INSERT INTO TENER VALUES ('Numancia','Nuevo Los Pajaritos');